# Intel Compilers
set(CMAKE_Fortran_COMPILER "mpiifort" CACHE STRING "" FORCE)
set(CMAKE_Fortran_FLAGS "-O3 -ip -fp-model precise -qopenmp" CACHE STRING "" FORCE)
set(Fortran_MIN_FLAGS "-O0 -fp-model precise" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER "icx" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "-O3 -fp-model precise -std=gnu99 -qopenmp" CACHE STRING "" FORCE)
set(LIB_PATHS "$ENV{MKLROOT}/lib/intel64 $ENV{HOME}/packages/fftw3xf/intel_23.1.0-mkl_2023.1 $ENV{HOME}/packages/slate/2023.06.00/intel_2023.1.0.x-cuda_12.1/opt/slate/lib $ENV{HOME}/packages/cosma/2.6.6/intel_2023.1.0.x-cuda_12.1/lib64 $ENV{CUDA_ROOT}/lib64" CACHE STRING "" FORCE)
set(INC_PATHS "$ENV{MKLROOT}/include/fftw $ENV{HOME}/packages/slate/2023.06.00/intel_2023.1.0.x-cuda_12.1/opt/slate/include" CACHE STRING "" FORCE)
set(LIBS "slate blaspp lapackpp slate_lapack_api cosma_prefixed_pxgemm cosma costa_prefixed_scalapack costa Tiled-MM cublas cudart mkl_intel_lp64 mkl_sequential mkl_core mkl_blacs_intelmpi_lp64 mkl_scalapack_lp64 fftw3xf_intel" CACHE STRING "" FORCE)
# set(LIBS "slate blaspp lapackpp slate_lapack_api cosma_prefixed_pxgemm cosma costa_prefixed_scalapack costa Tiled-MM cublas cudart mkl_intel_lp64 mkl_sequential mkl_core mkl_blacs_intelmpi_lp64 fftw3xf_intel" CACHE STRING "" FORCE)

set(USE_COSMA ON CACHE STRING "")
set(USE_SLATE ON CACHE STRING "")
set(USE_CUDA ON CACHE STRING "")
set(CMAKE_CUDA_COMPILER "nvcc" CACHE STRING "")
set(CMAKE_CUDA_FLAGS "-O3 -DAdd_ -arch=sm_80 -lcublas" CACHE STRING "")

set(USE_CALIPER ON CACHE STRING "")

set(USE_FFT_MKL ON CACHE BOOL "" FORCE)
set(USE_GREENX OFF CACHE BOOL "" FORCE)
set(USE_MPI ON CACHE BOOL "" FORCE)
set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
set(USE_LIBXC ON CACHE BOOL "" FORCE)
set(USE_HDF5 OFF CACHE BOOL "" FORCE)
set(USE_RLSY ON CACHE BOOL "" FORCE)
set(ELPA2_KERNEL "AVX512" CACHE STRING "Change to AVX/AVX2/AVX512 if running on Intel processors" FORCE)

# GNU Compilers
#set(CMAKE_Fortran_COMPILER ftn CACHE STRING "")
#set(CMAKE_Fortran_FLAGS "-O2 -fallow-argument-mismatch -ffree-line-length-none" CACHE STRING "")
#set(Fortran_MIN_FLAGS "-O0 -ffree-line-length-none" CACHE STRING "")
#set(CMAKE_C_COMPILER cc CACHE STRING "")
#set(CMAKE_C_FLAGS "-O2" CACHE STRING "")
#set(USE_MPI ON CACHE BOOL "" FORCE)
#set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
#set(USE_LIBXC ON CACHE BOOL "" FORCE)
#set(USE_HDF5 OFF CACHE BOOL "" FORCE)
#set(USE_RLSY ON CACHE BOOL "" FORCE)

# Cray Compilers
#set(CMAKE_Fortran_COMPILER ftn CACHE STRING "")
#set(Fortran_MIN_FLAGS "-O0" CACHE STRING "")
#set(CMAKE_Fortran_FLAGS "-O3 -hfp3" CACHE STRING "")
#set(CMAKE_C_COMPILER cc CACHE STRING "")
#set(CMAKE_C_FLAGS "-O2 -funroll-loops -ffast-math" CACHE STRING "")
#set(USE_MPI ON CACHE BOOL "" FORCE)
#set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
#set(USE_LIBXC ON CACHE BOOL "" FORCE)
