set(CMAKE_Fortran_COMPILER "mpifort" CACHE STRING "" FORCE)
# debug flags: -fcheck=all -fbacktrace
set(CMAKE_Fortran_FLAGS "-fc=gfortran-13 -g -Wall -O0 -fbacktrace -fcheck=bounds -Wno-unused-variable -Wno-unused-function -Wno-ampersand -Wno-tabs -Wno-unused-dummy-argument -Wuninitialized -fcheck=pointer -fallow-argument-mismatch -ffree-line-length-none -Wl,-lstdc++" CACHE STRING "" FORCE)
set(Fortran_MIN_FLAGS   "-fc=gfortran-13 -g -Wall -O0 -fbacktrace -fcheck=bounds -Wno-unused-variable -Wno-unused-function -Wno-ampersand -Wno-tabs -Wno-unused-dummy-argument -Wuninitialized -fcheck=pointer -fallow-argument-mismatch -ffree-line-length-none" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER "mpicc" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "-cc=gcc-13 -g -Wall -O0" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "mpicxx" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-cxx=g++-13 -g -Wall -O0" CACHE STRING "" FORCE)
set(LIB_PATHS "/opt/packages/scalapack/2.2.2/gcc-13.4.0-mpich-4.3.0-openblas /opt/homebrew/Cellar/openblas/0.3.29/lib" CACHE STRING "")
set(LIBS "scalapack openblas" CACHE STRING "" FORCE)
# for GreenX to use the same library
set(BLAS_LIBRARIES "-L/opt/homebrew/Cellar/openblas/0.3.29/lib -lblas" CACHE STRING "")
set(LAPACK_LIBRARIES "-L/opt/homebrew/Cellar/openblas/0.3.29/lib -llapack" CACHE STRING "")

set(USE_GREENX ON CACHE BOOL "" FORCE)
set(USE_MPI ON CACHE BOOL "" FORCE)
set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
set(USE_LIBXC ON CACHE BOOL "" FORCE)
set(USE_HDF5 OFF CACHE BOOL "" FORCE)
set(USE_RLSY ON CACHE BOOL "" FORCE)
set(ELPA2_KERNEL "" CACHE STRING "Change to AVX/AVX2/AVX512 if running on Intel processors" FORCE)
